### ISSUE TITLE
"cannot insert multiple commands into a prepared statement" even thought I use `interp False ...`

### ISSUE THREAD

**Issue by TheOddler** [awkward-squad/hasql-interpolate#12]
I'm getting the following error:

```
SessionUsageError (QueryError "DROP TYPE IF EXISTS gender_identity CASCADE;CREATE TYPE gender_identity AS ENUM ('abinary', 'agender', 'ambigender', 'androgyne', ...removed for brevity...)" [] (ResultError (ServerError "42601" "cannot insert multiple commands into a prepared statement" Nothing Nothing Nothing)))
```

However, I use `interp False`, which the docs say means if the statement should be prepared or not, but the error seems to say it is prepared. So either I'm misunderstanding, or there's a bug in the library perhaps?

**Comment by tstat** [comment]
The docs aren't very precise, and when combined with that error message I see how that would be confusing. Perhaps more detail should be added here and to `hasql`'s docs. 

That boolean argument is just passed along and becomes the boolean in [hasql's `Statement`](https://hackage.haskell.org/package/hasql-1.6.3.4/docs/Hasql-Statement.html#t:Statement). That bool controls whether a prepared statement will be made and arranged to be reused for the same query in the future of this session, instead of issuing another parse message. What is specifically relevant to this issue is that it controls which libpq call is issued (`PQsendQueryPrepared` or `PQsendQueryParams`). Either way, postgresql's extended query protocol is used, and consequently a prepared statement must be created. `PQsendQueryParams` just uses the "unnamed" prepared statement which is a special prepared statement in postgresql's extended query protocol for ephemeral usage (you can read about it [here](https://www.postgresql.org/docs/current/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY)).

The extended query protocol does not allow multiple sql statements to be made in a single prepare message, and that is the error you are seeing here. The simple query protocol does, and hasql allows you to use the simple protocol through [`sql`](https://hackage.haskell.org/package/hasql-1.6.3.4/docs/Hasql-Session.html#v:sql). 

So, you could use `sql` here instead of `interp` if you don't actually want to interpolate any arguments, or you break that multi statement string up into multiple `interp` calls.

**Comment by TheOddler** [comment]
I see! Thank you. The docs are indeed confusing, but essentially if I want multiple statements in one I have to use [sql](https://hackage.haskell.org/package/hasql-1.6.3.4/docs/Hasql-Session.html#v:sql), anything that goes strough a `Statement` won't allow multiple statements.

Before I was indeed using `sql`, but moved from `hasql-th` to `hasql-interpolate` and so moved this query from using `uncheckedSql` to the `sql` quasiquoter.

Thank you!
